on: 
    push:
        branches:
            - main
            - production
    workflow_dispatch:

jobs: 
    build: 
        runs-on: ubuntu-latest
    
        steps:
           - uses: actions/checkout@v5

           - name: Node.js action 
             uses: actions/setup-node@v4
             with: 
                node-version: '18.x'

           - name: Install npm
             run: |
                npm install
                npm test 
        
        

        